### ISSUE TITLE
[feature request] Connection schematic

### ISSUE THREAD

**Issue by silvioprog** [thalesfragoso/at28c-rs#1]
Hi.

It would be nice to add information about how to connect (e.g. which pins) the EEPROMs to the STM32 board.

cheers

**Comment by thalesfragoso** [comment]
There is a `Connections` section close to the end of the readme, since it's a simple design without external components I thought that it would be enough, do you think there is need for a more detailed one ?

**Comment by silvioprog** [comment]
Oh, I didn't see that. 😅 Thanks for clarifying!
